fix: entrypoint bug p3

diff --git a/home/docker/docker-compose-static-cdn.yml b/home/docker/docker-compose-static-cdn.yml
--- a/home/docker/docker-compose-static-cdn.yml
+++ b/home/docker/docker-compose-static-cdn.yml
@@ -33,24 +33,25 @@ services:
     volumes:
       - ./static-devarshi-dev-cdn:/sync/static-devarshi-dev
     restart: always
-    entrypoint: >
-      /bin/sh -c "
-        mc alias set minio http://minio-s3:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD || exit 1;
-        while true; do
-          echo 'Checking MinIO connection and starting sync at ' \$(date);
-          if mc ls minio/static-devarshi-dev; then
-            echo 'MinIO is accessible. Starting sync...';
-            if mc mirror --overwrite minio/static-devarshi-dev /sync/static-devarshi-dev; then
-              echo 'Sync completed successfully at ' \$(date);
-            else
-              echo 'Sync failed at ' \$(date);
-            fi
+    entrypoint: |
+      /bin/sh -c '
+      mc alias set minio http://minio-s3:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD || exit 1;
+      while true; do
+        echo "Checking MinIO connection and starting sync at $$(date)";
+        if mc ls minio/static-devarshi-dev; then
+          echo "MinIO is accessible. Starting sync...";
+          if mc mirror --overwrite minio/static-devarshi-dev /sync/static-devarshi-dev; then
+            echo "Sync completed successfully at $$(date)";
           else
-            echo 'MinIO not accessible. Retrying in 10 seconds...';
-            sleep 10;
+            echo "Sync failed at $$(date)";
           fi
-          sleep 60;
-        done"
+        else
+          echo "MinIO not accessible. Retrying in 10 seconds...";
+          sleep 10;
+        fi
+        sleep 60;
+      done
+      '
     networks:
       - internal
 
@@ -64,17 +65,18 @@ services:
       - AWS_SECRET_ACCESS_KEY=${AWS_STATIC_DEVARSHI_DEV_SECRET_KEY_ID}
       - AWS_DEFAULT_REGION=ap-south-1
     restart: always
-    entrypoint: >
-      /bin/sh -c "
-        while true; do
-          echo 'Starting AWS S3 backup at ' \$(date);
-          if aws s3 cp /sync/static-devarshi-dev s3://static-devarshi-dev-backup --recursive; then
-            echo 'AWS S3 backup completed successfully at ' \$(date);
-          else
-            echo 'AWS S3 backup failed at ' \$(date);
-          fi
-          sleep 3600;
-        done"
+    entrypoint: |
+      /bin/sh -c '
+      while true; do
+        echo "Starting AWS S3 backup at $$(date)";
+        if aws s3 cp /sync/static-devarshi-dev s3://static-devarshi-dev-backup --recursive; then
+          echo "AWS S3 backup completed successfully at $$(date)";
+        else
+          echo "AWS S3 backup failed at $$(date)";
+        fi
+        sleep 3600;
+      done
+      '
     networks:
       - internal
 
